name: IMPORT_M3U

on:
  schedule:
    - cron: '0 */12 * * *' # This runs every 12 hours, not 3
  workflow_dispatch: # This allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: zeknewbe/porong
          path: dest-repo

      - name: Import M3U File
        env:
          SOURCE_FILE_URL: https://raw.githubusercontent.com/jsosao/m3u/main/mylist.m3u8
          DEST_FILE_PATH: mylist.m3u8 # The destination path in the repository
        run: |
          cd dest-repo
          # Download the file using curl
          curl -o "${DEST_FILE_PATH}" "${SOURCE_FILE_URL}"
          
          # Check if there are any changes. If so, commit and push.
          if git diff --quiet; then
            echo "No changes in M3U file."
          else
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add "${DEST_FILE_PATH}"
            git commit -m "Imported M3U file from external source"
            git push
            echo "M3U file updated and pushed."
          fi
