name: IMPORT_M3U

on:
  schedule:
    - cron: '0 */12 * * *' # This runs every 12 hours
  workflow_dispatch: # This allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: zeknewbe/porong
          path: dest-repo

      - name: Import M3U File
        env:
          SOURCE_FILE_URL: https://raw.githubusercontent.com/jsosao/m3u/main/mylist.m3u8
          DEST_FILE_PATH: mylist.m3u8 # The destination path in the repository
        run: |
          cd dest-repo
          # Download the file using curl
          echo "Downloading file..."
          curl -o "${DEST_FILE_PATH}" "${SOURCE_FILE_URL}"
          
          # Check if the download was successful
          if [ -f "${DEST_FILE_PATH}" ]; then
            echo "Download successful, checking for changes..."
          else
            echo "Download failed, file does not exist."
            exit 1
          fi

          # Check for changes
          if git diff --quiet; then
            echo "No changes detected, no need to commit."
          else
            echo "Changes detected, proceeding to commit and push."
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add "${DEST_FILE_PATH}"
            git commit -m "Imported M3U file from external source"
            git push
            echo "M3U file updated and pushed."
          fi

