name: IMPORT_M3U

on:
  schedule:
    - cron: '0 */12 * * *' # This runs every 3 hours
  workflow_dispatch: # This allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: zeknewbe/porong
          path: dest-repo

      - name: Checkout source file
        uses: actions/checkout@v2
        with:
          repository: jsosao/m3u/main/mylist.m3u8
          path: source-repo
          fetch-depth: 0

      - name: Copy file if changed
        run: |
          SOURCE_FILE_PATH=source-repo/mylist.m3u8
          DEST_FILE_PATH=dest-repo/mylist.m3u8
          if [[ ! -f $DEST_FILE_PATH || $(diff $SOURCE_FILE_PATH $DEST_FILE_PATH) ]]; then
            cp $SOURCE_FILE_PATH $DEST_FILE_PATH
            echo "File updated"
            echo "FILE_UPDATED=true" >> $GITHUB_ENV
          else
            echo "No changes detected"
            echo "FILE_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Commit and push if updated
        run: |
          if [ "${{ env.FILE_UPDATED }}" = "true" ]; then
            cd dest-repo
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add andrewtv.m3u
            git commit -m "Auto update from source repository"
            git push
          fi
