name: IMPORT_M3U

on:
  schedule:
    - cron: '0 */12 * * *'  # This runs every 12 hours
  workflow_dispatch:  # This allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: zeknewbe/porong
          token: ${{ secrets.GITHUB_TOKEN }}
          path: dest-repo

      - name: Import M3U File
        env:
          GIT_EMAIL: visionintegral@gmail.com
          GIT_NAME: zeknewbe
          SOURCE_REPO: jsosao/m3u
          SOURCE_FILE: mylist.m3u8
          SOURCE_BRANCH: main
          DEST_PATH: mylist.m3u8
        run: |
          # Clone destination repo
          echo "Cloning destination repository..."
          git clone git@github.com:$GIT_NAME/porong.git dest-repo
          cd dest-repo || exit 1

          # Add source repo as a remote and fetch the file
          echo "Adding source repository as remote..."
          git remote add source_repo "https://github.com/$SOURCE_REPO.git"
          git fetch source_repo $SOURCE_BRANCH

          # Checkout the specific file from source repo
          echo "Checking out file from source repository..."
          if git checkout source_repo/$SOURCE_BRANCH -- "$SOURCE_FILE"; then
              if mv "$SOURCE_FILE" "$DEST_PATH"; then
                  echo "File moved to destination path."
              else
                  echo "Failed to move file to destination path."
                  exit 1
              fi
          else
              echo "Failed to checkout file from source repository."
              exit 1
          fi

          # Commit and push the changes
          echo "Setting up Git configuration..."
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_NAME"

          echo "Committing changes..."
          git add "$DEST_PATH"
          git commit -m "Imported $SOURCE_FILE from $SOURCE_REPO"

          echo "Pushing changes to the repository..."
          if git push origin main; then
              echo "File imported successfully!"
          else
              echo "Failed to push changes to destination repository."
              exit 1
          fi
