name: IMPORT_M3U

on:
  schedule:
    - cron: '0 */12 * * *'  # This runs every 12 hours
  workflow_dispatch:  # This allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: zeknewbe/porong
          path: dest-repo

      - name: Import M3U File
        env:
          SOURCE_FILE_URL: https://raw.githubusercontent.com/jsosao/m3u/main/mylist.m3u8
          DEST_FILE_PATH: mylist.m3u8  # The destination path in the repository
        run: |
          cd dest-repo
          # Download the file using curl
          echo "Downloading file from ${SOURCE_FILE_URL}"
          curl -sS -o "${DEST_FILE_PATH}" "${SOURCE_FILE_URL}" || {
            echo "Failed to download the file."
            exit 1
          }
          echo "File downloaded successfully."

          # Check for changes
          echo "Checking for changes..."
          git status
          git diff
          if git diff --quiet; then
            echo "No changes detected, no need to commit."
          else
            echo "Changes detected, proceeding to commit and push."
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add "${DEST_FILE_PATH}"
            git commit -m "Update M3U file from external source"
            git push
            echo "M3U file updated and pushed."
          fi
