name: IMPORT_M3U

on:
  schedule:
    - cron: '0 */12 * * *'  # This runs every 12 hours
  workflow_dispatch:  # This allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the destination repository where the file will be pushed
      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: zeknewbe/porong
          path: dest-repo

      # Checkout the specific file from the source repository
      - name: Checkout source file
        uses: actions/checkout@v2
        with:
          repository: jsosao/m3u
          path: source-repo
          ref: main  # Make sure to use the correct branch here

      # Copy the file from the source repository to the destination repository
      - name: Copy and commit file
        run: |
          # Assuming the file is in the root of the source repository
          SOURCE_FILE_PATH=source-repo/mylist.m3u8
          DEST_FILE_PATH=dest-repo/mylist.m3u8

          # Copy the file from source to destination
          cp -f $SOURCE_FILE_PATH $DEST_FILE_PATH
          
          # Change to the destination repository directory
          cd dest-repo
          
          # Configure Git
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          # Commit and push the changes if there are any
          if ! git diff --quiet; then
            git add $DEST_FILE_PATH
            git commit -m "Imported mylist.m3u8 from source repository"
            git push
            echo "File imported and pushed to destination repository."
          else
            echo "No changes detected, nothing to commit."
          fi
